import type { Messages } from "./index.js";

const DYNAMIC_MESSAGES: Readonly<Record<string, string>> = {
  each: "Table-driven with it.each / test.for. The data rows are not expanded",
  loop: "Declared inside a loop. The number of tests and their names are decided at runtime",
  title: "The test name is built from an expression. The actual name is decided at runtime",
  body: "A function reference is passed as the body, so its content cannot be analyzed",
};

/** 「1 file」「2 files」のように数と単語をつなげる */
const plural = (n: number, word: string) => `${n} ${word}${n === 1 ? "" : "s"}`;

/** duplicate-body で名前を挙げるテストの上限（残りは件数だけ示す） */
const MAX_SHOWN_TESTS = 3;

export const en: Messages = {
  title: "Test specification",
  staticAnalysis: "Static analysis (tests were not run)",
  verdicts: { error: "Needs fix", warn: "Needs review", ok: "OK" },
  modifiers: {
    skip: { label: "Skipped", title: ".skip / .fixme: not run" },
    only: { label: "only", title: ".only: only this test runs" },
    todo: { label: "Todo", title: ".todo: a name without a body" },
    each: { label: "Data-driven", title: "it.each etc.: generated at runtime for each data row" },
  },
  stepVerbs: {
    goto: "Open",
    reload: "Reload",
    goBack: "Back",
    goForward: "Forward",
    click: "Click",
    dblclick: "Double-click",
    tap: "Tap",
    fill: "Fill",
    type: "Type",
    pressSequentially: "Type",
    insertText: "Type",
    press: "Press",
    down: "Key down",
    up: "Key up",
    check: "Check",
    uncheck: "Uncheck",
    setChecked: "Set checked",
    selectOption: "Select",
    selectText: "Select text",
    hover: "Hover",
    focus: "Focus",
    blur: "Blur",
    clear: "Clear",
    setInputFiles: "Set files",
    dragTo: "Drag",
    dragAndDrop: "Drag",
    move: "Move mouse",
    wheel: "Scroll",
    waitForTimeout: "Wait",
  },
  mock: { label: "Mock", title: "Replaces a real dependency with a stand-in" },
  noAssertions: { todo: "Not implemented", none: "None" },
  rules: {
    "no-assertions": {
      label: "No expect",
      description: "Has no assertions (expect etc.)",
      why: "It only runs the code and never checks the result. The test passes even if the implementation is broken.",
      fix: "Check the result that the test name promises with expect. e.g. expect(result).toBe(expected)",
    },
    "focused-test": {
      label: ".only left in",
      description: ".only is left in",
      why: "Other tests in the same file do not run, so their failures go unnoticed.",
      fix: "Remove .only.",
    },
    "skipped-test": {
      label: "skip / todo left in",
      description: ".skip / .fixme / .todo is left in",
      why: "It does not run, so it guarantees nothing.",
      fix: "Fix and enable it, or delete it. If you keep it, leave a comment explaining why.",
    },
    "weak-assertions-only": {
      label: "Only toBeTruthy",
      description: "Only checks truthiness or existence (toBeTruthy / toBeDefined etc.)",
      why: "toBeTruthy / toBeDefined only check that a value exists. A wrong value still passes.",
      fix: "Compare with the specific expected value. e.g. expect(date).toEqual(new Date(2026, 8, 29))",
    },
    "snapshot-only": {
      label: "Only snapshots",
      description: "Only compares snapshots",
      why: "It only checks that the result matches the previous one, so the test does not say what the correct result is. A wrong result saved as the snapshot goes unnoticed.",
      fix: "Check important values explicitly with toBe / toEqual, and use snapshots only as a supplement.",
    },
    "mock-calls-only": {
      label: "Only mock calls",
      description: "Only verifies mock calls and never looks at the result",
      why: "It only checks that a mock was called, not that the result is correct.",
      fix: "Also check the return value and the changes to the screen or data with expect.",
    },
    "conditional-assertion": {
      label: "expect in a branch",
      description: "Has assertions inside a branch (if / ternary / && / switch / catch)",
      why: "Depending on the condition, expect may not run, and the test passes without checking anything.",
      fix: "Remove the branch so that expect always runs. Use toThrow() / rejects to check exceptions.",
    },
    "fixed-wait": {
      label: "Fixed-time sleep",
      description: "Waits for a fixed time (waitForTimeout / sleep etc.)",
      why: "It causes failures in slow environments and wastes time in fast ones.",
      fix: "Wait for the screen or state to change. e.g. await expect(page.getByText('Done')).toBeVisible()",
    },
    "dynamic-test": {
      label: "Generated by each / loop",
      description: "Generated dynamically by it.each or a loop, and cannot be expanded by static analysis",
      why: "The tests are generated at runtime, so this specification cannot show how many there are or what data they use.",
      fix: "Check the data passed to each, or the loop, in the source.",
    },
    "duplicate-title": {
      label: "Same test name",
      description: "Another test in the same describe has the same name",
      why: "When one of them fails, you cannot tell which one failed.",
      fix: "Rename them so that the names say what they check.",
    },
    "duplicate-body": {
      label: "Same test body",
      description: "Another test has the same body (ignoring comments and whitespace)",
      why: "It checks the same thing twice and inflates the number of tests.",
      fix: "Merge them, or rewrite one to check a different case (boundary values, error cases, etc.).",
    },
  },
  warning(w) {
    const d = w.detail ?? {};
    switch (w.rule) {
      case "no-assertions":
        return "No result is checked with expect or similar";
      case "focused-test":
        return ".only is left in. Other tests in the same file do not run";
      case "skipped-test":
        return d.reason === "todo" ? "Still a .todo without a body" : "Skipped with .skip / .fixme";
      case "weak-assertions-only":
        return "Only checks truthiness or existence with toBeTruthy / toBeDefined etc., not the value";
      case "snapshot-only":
        return "Only verified by comparing snapshots";
      case "mock-calls-only":
        return "Only verifies mock calls and never checks the result (return value or state)";
      case "conditional-assertion":
        return "expect is inside a branch and may not run";
      case "fixed-wait":
        return d.code ? `Waits for a fixed time: ${d.code}` : "Waits for a fixed time";
      case "dynamic-test":
        return (
          (d.reason && DYNAMIC_MESSAGES[d.reason]) || "Generated dynamically and cannot be expanded by static analysis"
        );
      case "duplicate-title":
        return d.lines
          ? `${d.lines.length} tests in the same describe have the same name (lines ${d.lines.join(", ")})`
          : "Another test in the same describe has the same name";
      case "duplicate-body": {
        if (!d.tests?.length) return "Another test has the same body";
        const shown = d.tests.slice(0, MAX_SHOWN_TESTS).map((t) => `"${t.title}" (${t.path}:${t.line})`);
        const rest = d.tests.length - shown.length;
        return `Same body as ${shown.join(", ")}${rest > 0 ? ` and ${rest} more` : ""}`;
      }
      default:
        return w.rule;
    }
  },
  markdown: {
    issues: "Issues",
    issuesHeader: ["Verdict", "Issue", "Count"],
    caseHeader: ["No.", "Test", "Steps", "Expected", "Verdict"],
    noTests: "No tests found",
    outsideDescribe: "(outside describe)",
    modifier: (label) => `[${label}]`,
  },
  csv: {
    header: [
      "No.",
      "File",
      "Framework",
      "describe",
      "Test",
      "Modifiers",
      "Steps",
      "Expected",
      "Verdict",
      "Issues",
      "Line",
    ],
    listSeparator: ", ",
  },
  html: {
    filterByVerdict: "Filter by verdict",
    filterByFramework: "Filter by framework",
    filterByRule: "Filter by issue",
    search: "Search",
    searchLabel: "Search (test names, steps, expected results, file names)",
    expandAll: "Expand all",
    collapseAll: "Collapse",
    switchTheme: "Switch theme",
    themes: { auto: "Theme: follow the OS", light: "Theme: light", dark: "Theme: dark" },
    all: "All",
    noIssues: "No issues",
    ruleChipTitle: "{description} ({id})",
    openDetails: "Open the details of {no}",
    columns: { no: "No.", title: "Test", steps: "Steps", expected: "Expected", verdict: "Verdict" },
    jumpToLine: "Line {line} →",
    issues: "Issues",
    why: "Why",
    fix: "Fix",
    source: "Source",
    assertLine: "Assertion",
    warnLine: "Issue",
    noTests: "No tests found",
    noResults: "No matching tests",
    clearFilters: "Clear filters",
  },
  cli: {
    help: `testglass — generate a test specification for review from your test code

Usage:
  testglass [options]                   Read the tests and generate spec.json and the outputs (HTML)
  testglass collect [options]           Read the tests and overwrite spec.json
  testglass render <spec.json> [opts]   Generate the outputs from spec.json
  testglass schema [--out <file>]       Print the JSON Schema of spec.json

Options:
  --root <dir>        Root directory to analyze (default: the current directory)
  --out <file>        Where to write spec.json (default: testglass/spec.json)
  --format <names>    Output formats (comma-separated html / md / csv. default: html)
  --out-dir <dir>     Where to write the outputs (default: the directory of spec.json)
  --lang <lang>       Language of the outputs and messages (ja / en. default: ja)
  --config <file>     Config file (default: testglass.config.{mjs,js,json} in the root)
  --fail-on <level>   Exit with code 1 if there is at least one error / warn warning
  -h, --help          Show this help
  -v, --version       Show the version
`,
    seeHelp: "Run `testglass --help --lang en` for usage.",
    collected: (s) =>
      `✔ Analyzed ${plural(s.files, "file")} / ${plural(s.tests, "test")} → ${s.path}\n` +
      `  Warnings: error ${s.errors} / warn ${s.warns} (${plural(s.testsWithWarnings, "test")} with warnings)`,
    unmatched: (paths) =>
      `  Files that matched no input adapter (${paths.length}):\n` +
      paths.map((p) => `    - ${p}\n`).join("") +
      "  If the automatic detection is wrong, specify them with frameworks in the config file.",
    rendered: (format, path) => `✔ Wrote ${format} → ${path}`,
  },
  errors(e) {
    switch (e.code) {
      case "config-not-found":
        return `Config file not found: ${e.path}`;
      case "config-not-object":
        return `The config file must export an object: ${e.path}`;
      case "invalid-lang":
        return `${e.option} must be one of ${e.langs.join(" / ")} (got: ${JSON.stringify(e.value)})`;
      case "unknown-framework-adapter":
        return `Unknown adapter in frameworks: "${e.name}"`;
      case "rules-not-object":
        return "rules must be an object";
      case "unknown-rule":
        return `Unknown rule: "${e.rule}" (available rules: ${e.rules.join(", ")})`;
      case "invalid-rule-value":
        return `The value of rule "${e.rule}" must be "off" / "warn" / "error" (got: ${JSON.stringify(e.value)})`;
      case "invalid-fail-on":
        return `--fail-on must be error or warn (got: ${e.value})`;
      case "extra-args":
        return `Unexpected arguments: ${e.args.join(" ")}`;
      case "missing-spec-path":
        return "render needs the path to spec.json";
      case "unknown-command":
        return `Unknown command: ${e.command}`;
      case "unknown-format":
        return `Unknown output format: ${e.format} (available formats: ${e.formats.join(", ")})`;
      case "unreadable-spec":
        return `Cannot read spec.json: ${e.path} (${e.reason})`;
      case "unsupported-schema":
        return `Unsupported schemaVersion: ${String(e.version)} (this version supports ${e.supported})`;
    }
  },
};
